In [1]:
import pandas as pd 
import numpy as np

In [5]:
df= pd.read_csv(r"college_student_placement_dataset.csv")

In [6]:
df.sample(5)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
8394,CLG0022,87,6.39,6.32,4,No,1,4,2,No
2677,CLG0064,76,9.17,8.96,8,Yes,10,1,0,No
923,CLG0001,89,7.11,7.31,8,No,5,1,0,No
2133,CLG0098,108,9.05,9.48,8,Yes,0,2,2,No
7389,CLG0010,112,5.72,5.27,5,No,0,5,0,No

In [7]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [12]:
df=df.drop(columns="College_ID")

In [13]:
df

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,No
1,97,5.52,5.37,8,No,7,8,0,No
2,109,5.36,5.83,9,No,3,1,1,No
3,122,5.47,5.75,6,Yes,1,6,1,No
4,96,7.91,7.69,7,No,8,10,2,No
...,...,...,...,...,...,...,...,...,...
9995,119,8.41,8.29,4,No,1,8,0,Yes
9996,70,9.25,9.34,7,No,0,7,2,No
9997,89,6.08,6.25,3,Yes,3,9,5,No
9998,107,8.77,8.92,3,No,7,5,1,No
9999,109,9.41,9.77,8,No,3,5,5,No

In [17]:
input_vars=df.iloc[:,:-1]

In [18]:
input_vars

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
0,107,6.61,6.28,8,No,8,8,4
1,97,5.52,5.37,8,No,7,8,0
2,109,5.36,5.83,9,No,3,1,1
3,122,5.47,5.75,6,Yes,1,6,1
4,96,7.91,7.69,7,No,8,10,2
...,...,...,...,...,...,...,...,...
9995,119,8.41,8.29,4,No,1,8,0
9996,70,9.25,9.34,7,No,0,7,2
9997,89,6.08,6.25,3,Yes,3,9,5
9998,107,8.77,8.92,3,No,7,5,1
9999,109,9.41,9.77,8,No,3,5,5

In [25]:
df.isnull().value_counts()

IQ     Prev_Sem_Result  CGPA   Academic_Performance  Internship_Experience  Extra_Curricular_Score  Communication_Skills  Projects_Completed  Placement
False  False            False  False                 False                  False                   False                 False               False        10000
Name: count, dtype: int64

so there are no null values

# now we build  a transformer :

In [26]:
from sklearn.compose import ColumnTransformer

In [29]:
input_vars.iloc[0]

IQ                         107
Prev_Sem_Result           6.61
CGPA                      6.28
Academic_Performance         8
Internship_Experience       No
Extra_Curricular_Score       8
Communication_Skills         8
Projects_Completed           4
Name: 0, dtype: object

# we will apply :
1) onehot-->Internship_Experience
2) ordinal-->
3) standardscaler--> iq ,prev_sem, acadamic prformance, project_completed,commu_skills,

In [50]:
one_hot_list=["Internship_Experience"]
standard_s_list = input_vars.drop(columns="Internship_Experience").columns
type(one_hot_list)

list

In [57]:
standard_s_list=list(standard_s_list)

In [54]:
input_vars.columns

Index(['IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed'],
      dtype='object')

In [56]:
df["Internship_Experience"].value_counts()

Internship_Experience
No     6036
Yes    3964
Name: count, dtype: int64

In [55]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [58]:
preprocessor=ColumnTransformer(
    transformers=[
    ("tf1",OneHotEncoder(categories=[["No","Yes"]]),one_hot_list),
    ("tf2",StandardScaler(),standard_s_list) ],
    remainder="passthrough"

)

In [60]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [61]:
model_pipeline=Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("model",LogisticRegression(max_iter=1000, class_weight='balanced'))
    ]
)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x=input_vars

In [64]:
x

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
0,107,6.61,6.28,8,No,8,8,4
1,97,5.52,5.37,8,No,7,8,0
2,109,5.36,5.83,9,No,3,1,1
3,122,5.47,5.75,6,Yes,1,6,1
4,96,7.91,7.69,7,No,8,10,2
...,...,...,...,...,...,...,...,...
9995,119,8.41,8.29,4,No,1,8,0
9996,70,9.25,9.34,7,No,0,7,2
9997,89,6.08,6.25,3,Yes,3,9,5
9998,107,8.77,8.92,3,No,7,5,1
9999,109,9.41,9.77,8,No,3,5,5

In [75]:
y=df["Placement"]

In [80]:
y

0        No
1        No
2        No
3        No
4        No
       ...
9995    Yes
9996     No
9997     No
9998     No
9999     No
Name: Placement, Length: 10000, dtype: object

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,stratify=y)

In [83]:
x_train

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
2350,115,5.96,6.34,8,Yes,8,2,2
9555,130,8.16,7.89,5,Yes,0,2,5
8388,91,9.80,9.60,3,No,9,5,0
5830,96,5.65,5.30,7,Yes,3,8,3
5116,125,6.18,6.28,4,No,1,5,2
...,...,...,...,...,...,...,...,...
4439,107,9.56,9.71,6,No,8,4,5
3972,105,8.24,8.24,6,Yes,0,10,3
1992,117,9.21,9.29,8,No,9,7,5
3423,106,7.98,8.26,2,No,8,6,4
6581,103,8.06,8.19,4,No,1,2,1

In [84]:
y_train

2350     No
9555     No
8388     No
5830     No
5116     No
       ...
4439     No
3972    Yes
1992    Yes
3423     No
6581     No
Name: Placement, Length: 7500, dtype: object

In [87]:
model_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('tf1',
                                                  OneHotEncoder(categories=[['No',
                                                                             'Yes']]),
                                                  ['Internship_Experience']),
                                                 ('tf2', StandardScaler(),
                                                  ['IQ', 'Prev_Sem_Result',
                                                   'CGPA',
                                                   'Academic_Performance',
                                                   'Extra_Curricular_Score',
                                                   'Communication_Skills',
                                                   'Projects_Completed'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [88]:
from sklearn.metrics import accuracy_score

In [90]:
result_train= model_pipeline.predict(x_train)
result_test= model_pipeline.predict(x_test)

In [91]:
acc_train=accuracy_score(result_train,y_train)*100
acc_test=accuracy_score(result_test,y_test)*100

In [92]:
print(f"the model accuracy from tarining data is {acc_train}")

the model accuracy from tarining data is 85.26666666666667

In [93]:
print(f"the model accuracy from testing data is {acc_test}")

the model accuracy from testing data is 84.36

# we got 84.36 accuracy from our testing data